### ISSUE TITLE
Version of the requirement of python package, especially tensorflow.

### ISSUE THREAD

**Issue by Annie98** [titu1994/keras-coordconv#17]
can you just list the version of the requriement of python packages, especially tensorflow?

**Comment by titu1994** [comment]
Tensorflow 1.12+ should be fine. Not tested with 2.0, but latest Keras from pypi does support Tensorflow 2 so I expect it to work.

**Comment by Annie98** [comment]
Many thanks for your replying. I use tensorflow 1.15.0 and keras 2.3.1, but with the problem as follow:
**
/home/anni/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/anni/code/Contouring/Code/Models/coordUnet.py", line 119, in <module>
    m = cdunet(5, 256, 256)
  File "/home/anni/code/Contouring/Code/Models/coordUnet.py", line 16, in cdunet
    x = CoordinateChannel2D()(img_input)
  File "/home/anni/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 881, in __call__
    inputs, outputs, args, kwargs)
  File "/home/anni/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2043, in _set_connectivity_metadata_
    input_tensors=inputs, output_tensors=outputs, arguments=arguments)
  File "/home/anni/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2059, in _add_inbound_node
    input_tensors)
  File "/home/anni/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/util/nest.py", line 536, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/anni/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/util/nest.py", line 536, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/anni/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2058, in <lambda>
    inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
AttributeError: 'tuple' object has no attribute 'layer'
**
And this is my code:
`
from keras.models import Model
from keras.applications import vgg16
from keras.layers import Input, BatchNormalization, Activation, concatenate
from keras.layers import Conv2D, UpSampling2D, MaxPooling2D
import sys
sys.path.append('../')
from coord import CoordinateChannel2D


def cdunet(nClasses, input_height, input_width):
    img_input = Input(shape=(input_height, input_width, 1))
    x = CoordinateChannel2D()(img_input)
    ft = Conv2D(filters=3,
                kernel_size=3,
                padding='same',
                kernel_initializer='glorot_normal',
                bias_initializer='zeros'
                )(x)
    md = Model(inputs=img_input, outputs=ft)
    vgg_streamlined = vgg16.VGG16(include_top=False, weights=None, input_tensor=md.output)
    assert isinstance(vgg_streamlined, Model)
......
`
I also try the version of tensorflow such as 1.13.2 ,1.14.0 and 1.12.0, but all of those have some problem. Could you help me? Thank you !

**Comment by titu1994** [comment]
I don't know what the issue is here. Seems internally Keras error somewhere. I've stopped working with base Keras, and have just been moving stuff to TF.keras as an alternative. 

If you'd like I could probably port this module to tf.keras instead.

**Comment by Annie98** [comment]
Thanks, and Good Luck!
