### ISSUE TITLE
3D CoordConv on GPU

### ISSUE THREAD

**Issue by socathie** [titu1994/keras-coordconv#8]
I encounter the following error when running on GPU (using Theano) with a 3D single-channel input, the same model compiles fine on my personal laptop (using Tensorflow).

```
Traceback (most recent call last):
  File "vgg_coord.py", line 52, in <module>
    model = VoxCoordCNN(x_vol, y_vol, z_vol)
  File "vgg_coord.py", line 22, in VoxCoordCNN
    out = CoordinateChannel3D()(X)
  File "/share1/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/data/cathie/cnn/coord.py", line 143, in call
    xx_ones = K.ones(K.stack([batch_shape, dim3]), dtype='int32')
  File "/share1/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 310, in ones
    return variable(np.ones(shape), dtype, name)
  File "/share1/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/numpy/core/numeric.py", line 188, in ones
    a = empty(shape, dtype, order)
TypeError: expected sequence object with len >= 0 or a single integer
```

I am out of my depth when it comes to working with backend..

**Comment by titu1994** [comment]
> File "/share1/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 310, in ones
    return variable(np.ones(shape), dtype, name)

Oh Theano. This occurs because Theano does not support a Tensor for its shape definition. It delegates the tensor building to Numpy first, and then wraps that ndarray into a Theano tensor.

Since batch size is unknown at model building time (it is generally set to None), therefore there is no way to pass the shape [batch_size, dim3] to the numpy array dynamically. 

This needs a fix in the Keras backend, or a rewrite of the code + specifying a static batch size for the input shape in order to work on Theano.

I would suggest working with TF or CNTK for now.

**Comment by titu1994** [comment]
It would require a rewrite of the script as well, removing all of the K.stack() and only passing the shape arrays directly.

**Comment by titu1994** [comment]
I just added a theano specific version of the script, called `coord_theano.py`. I think that may work, combined with a static batch shape.
